server:
  address: :8080
mongodb:
  uri: mongodb://localhost:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.15
  database: logs
internals:
  isLogDependenciesCreated: true
